# Site settings
title: Pointing to the Moon
description: Blog of Yingkai Liu
baseurl: "" 
url: "https://yk-liu.github.io" 

# GitHub User settings
username: Yingkai Liu
github_username: yk-liu
user_description: A Physics undergrad with a broad interest
user_title: Physics Undergraduate
email: yingkai.liu@outlook.com

# Blog Author settings
author:
  name:           Yingkai Liu
  picture:        
  email:          yingkai.liu@outlook.com
  description:    I'm a Physics undergrad with a broad interest.
  twitter:
  facebook:
  github:         https://github.com/yk-liu
  linkedin:
  # # If you're forking this site, make sure you delete this entry!
  clustrmap:      MlqUzlcZFdHetSQuxml5oHyt9RwVjZrsGbvyaRpMwgU 
  # If you're forking this site, make sure you delete this entry!


# markdown
markdown: kramdown

future: true
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
 - "*.source.*"